### ISSUE TITLE
Hiyo, a few questions and an idea!

### ISSUE THREAD

**Issue by thedeerirty** [Novarch129/JoJo-s-Bizarre-Survival#15]
Hey! Not exactly sure if this is the method I should use to contact you, or grab your attention. Frankly, I'm not used to this site at all and if this is in anyway, shape, or form inconvient, then I humbly apologize. Just had a few things I wanted to say and this seemed the best way to do it without emailing you. Email tends to be a bit more of a private things for a person so I thought contacting you that way would probably be ruder than this.

So! This my dude, is a spicy looking mod so-far. Spicier than most jojo mods I've seen! 

Did you happen to post anywhere what version this is for? I _doubt_ it will be, but I'm secretly hoping for 1.12 release. Its a classic minecraft modding time with a lot of mods I could pair with this one! I saw you mentioned a 1.16 port, and also mentioned KnightDemon's mod, so it got me hoping. If I had the money, I'd even donate some if it could help get this on 1.12.
However, while I am no coder, I do here forward or backward porting a mod is _very hard._ So I can understand being hesitant to do so. Hell, maybe I'll even learn how to code just to do a backport, lol.
I mostly play on 1.12 though, so if it doesn't happen to be on there I most likely won't check it out. Sorry. 

Well, regardless, you mentioned on the Stand Page you couldn't think of a good way of implementing Epitath, for King Crimson? I thought of an idea, or rather, discovered an idea that might inspire you. [This](https://www.curseforge.com/minecraft/mc-mods/mahou-tsukai) magic mod has a spell called Clairvoyance, I believe? From what I can tell, it basically shows you the pathing of a hostile mob that has targetted you, before it actually moves there. Not sure if that information could be of use to you, but I thought it might be something to think about.

Is there a Discord, or Curse, or something that I could also join? Even if it isn't for 1.12 i'm still really excited for this mod as it really does seem like the best out there, and you've put the time into making it, and that's something I gotta respect.

Anyway, thank you for your time.

**Comment by Novarch129** [comment]
> Did you happen to post anywhere what version this is for?

It's for 1.15 and 1.16 (eventually, when we finally get a stable release of Forge 1.16), I don't think I'll be making a 1.12 port, but nothing is definitive yet, FYI there might even be a Fabric port coming, compared to that 1.12 might be easy, I'll look into into it when I have some spare time.

> I do here forward or backward porting a mod is _very hard_

Depends really, I can't really think of anything that would be _too_ hard to backport to 1.12, actually, porting up to 1.16 may be a bit harder with the dimension rewrite, it really depends on the version, for instance world gen got completely overhauled 1.12 -> 1.13, thankfully, my mod doesn't use world gen too much.

> you mentioned on the Stand Page

People read that? I'm glad to here my work didn't go unnoticed!

> [This](https://www.curseforge.com/minecraft/mc-mods/mahou-tsukai) magic mod has a spell called Clairvoyance, I believe? From what I can tell, it basically shows you the pathing of a hostile mob that has targetted you, before it actually moves there.

From that brief description it sounds like **exactly** what I need, great find!

> Is there a Discord, or Curse, or something that I could also join?

I'm working on a Discord currently, I'll post it in the [README](https://github.com/Novarch129/JoJo-s-Bizarre-Survival/blob/1.15.x/README.md) when it's done.

**Comment by thedeerirty** [comment]
Wow you caught me just as I was about to lay down, nice! Glad to hear from you today!

Again, from what you have shown here I'm super impressed with the work you are doing. It honestly seems like it could be the best jojo mod around. Don't get me wrong, I'm not saying Steve's Bizzare Adventure and that other one are bad or anything; it simply appears you are making a better one. 

As for the 1.12 port, I'd be super stoaked for that. Whilst it is an old version, I do feel as if you could get a sizeable chunk of more downloads or attention (if that is apart of your goal) by also including that as a version. Lot of the great classic mods like Thaumcraft, Tough as Nails, etc. are still only for that version, and I certainly like those. That being said, even if it doesn't happen its nice to hear that you at least thought about it.

Yeah! I saw that somewhat small mod the other day and it reminded me of King Crimson. He is my favorite stand in the series. I also had the thought that perhaps the Crimson Effect on Mobs/Players could temporarily given them a different AI or pathing? Instead of players just being slower, it could give the feeling of losing control. Again, I'm no coder so I'm not sure how that could be done. [Lycanites Mobs](https://www.curseforge.com/minecraft/mc-mods/lycanites-mobs) has a few status effects that seem to let you lose control of your character in the form of the Fear and Instability debuffs, but that's the only example I could think of. 

Hell yeah! Once that discord is up I'll join and try to spread it around like wildfire.

Anyway, thank you for responding to me!

**Comment by thedeerirty** [comment]
If you are replying as of current, I'll have to reply when I wake up. It is very late (or early) for me, sorry 
Have a nice day!

**Comment by thedeerirty** [comment]
Hey! Good day! Sorry to bug you yet again, but I did have a few more things I'd like to ask or say before you close the issue. I think its pretty late for you currently? So yet again, sorry to bug you.

The questions I still have are as followed:

- Will you include a config to enable or disable some stands abilities? I feel like, on a server at least, other players losing all of their stuff due to Made in Heaven might get a bit well. Grief-like, you know?

-Will stands have the ability to block projcetiles, or at least, arrows? I feel like, since they aren't stands themselve, arrows could be akin to say, blocking bullet. Maybe you could punch them out of the air>

-Speaking of the punching, I'm curious to how yours work! Is it similar to the Steve's Bizzare adventure, where when your stand is summoned, you left click to punch?

**Comment by Novarch129** [comment]
> Sorry to bug you yet again

It's alright, part of making a mod is dealing with the community, questions and suggestions are completely natural.

> * Will you include a config to enable or disable some stands abilities?

Of course I will, it seems like a very important feature, I already have some config options, but they're either cosmetic or there for fun.

> due to Made in Heaven

I'm gonna make getting him painfully hard, killing mobs, going to specific coordinates, getting rare items, IMO if you get him you deserve being able to do whatever you want, but yes, you will be able to disable him if you so desire.

> * Will stands have the ability to block projectiles

If you wish so, yes. If you don't want to do anything to it it'll just go right through the Stand.

> * you left click to punch

Exactly like that, I think that's the most intuitive approach for Stand attacks currently, specials will be on X and P by default, ability toggling on Y.

As a final remark I'll say that the mod is _technically_ playable right now, if you wish to download the mod go to either the 1.15.x or master branch and click "Code" then "Download ZIP", extract the .zip and run the build.bat file included, you're cmd will appear for a minute or two and build the mod, when it's gone go to "folderYouExtractedTo/build/libs/JoJoBizarreSurvival-1.15.2-0.0.1.0.jar" there you will find the mod .jar, make sure to use 1.15.2 latest Forge, recommended will not work.
I hope being able to play the mod will help in giving feedback, just remember that the mod is still in development, so not everything is done yet (Stand evolution, obtaining Stands in survival, etc.), thanks for the feedback!

**Comment by GonnahelpNovarchsomehow** [comment]
I'm ngl, this is one of the best JoJo mods, scratch that, THIS IS THE BEST JOJO MOD, now, I have some questions and suggestions,  I know thedeerirty already made a comment about Epitaph, but I got a suggestion but mine is a bit simpler, In A Bizarre Day, Roblox, when the user uses Epitaph, the user doesn't take damage, that is because of Epitaph predicting the moves. Another suggestion, I recommend adding an option to disable the time stop animation, cause my PC is an old one and it had trouble with the animation, not because it sucked, but because my PC couldn't handle it, but I get steady 40 fps, the point is, there might be other Minecraft users who has an old computer like me, overall this is a great PC, it can handle TF2 but can't handle a simple animation, lmao. For the questions.
1. Any ideas for a release date yet? I'm not trying to rush you, if you feel like I did, I apologize, I'm just so pumped up for this mod.
2.I saw that you are making a discord server? I voted there, if you can, you might add an Suggestions Chat, Help And Bugs chat, and an announcements chat.
3.Is the Tusk one gonna be 4 separate ones or is it gonna be only one?
4. Similar to the 3rd question, but with Echoes.
If you answer this, Thank you, I love this upcoming mod, and Have a nice day/night!

**Comment by thedeerirty** [comment]
> As a final remark I'll say that the mod is _technically_ playable right now, if you wish to download the mod go to either the 1.15.x or master branch and click "Code" then "Download ZIP", extract the .zip and run the build.bat file included, you're cmd will appear for a minute or two and build the mod, when it's gone go to "folderYouExtractedTo/build/libs/JoJoBizarreSurvival-1.15.2-0.0.1.0.jar" there you will find the mod .jar, make sure to use 1.15.2 latest Forge, recommended will not work.
> I hope being able to play the mod will help in giving feedback, just remember that the mod is still in development, so not everything is done yet (Stand evolution, obtaining Stands in survival, etc.), thanks for the feedback!

Not sure if I'm using the quote system right, this site is rather new to me. Anyway, I've run into a small issue that i may just not be understand, or being a bit dumb about? When I try to run the .bat, either by clicking on it or running it as admin, the cmd will appear for a very brief moment before disappearing. Is that normal, and should I just wait?

**Comment by Novarch129** [comment]
> Is that normal, and should I just wait?

It is, just wait for a while and then check the folder.

**Comment by Novarch129** [comment]
> Any ideas for a release date yet? I'm not trying to rush you, if you feel like I did, I apologize, I'm just so pumped up for this mod.

1.15 and possibly 1.16 this month, 1.12  would be late next month if I started work on it right now. Fabric would be late October or November, really hard to port.

> I saw that you are making a discord server? I voted there, if you can, you might add an Suggestions Chat, Help And Bugs chat, and an announcements chat.

Agreed, that should be dropping today.

> Is the Tusk one gonna be 4 separate ones or is it gonna be only one?
> Similar to the 3rd question, but with Echoes.

All Stand acts will be treated as a separate Stand, they will have their respective abilities and the ability to switch to lower acts.

> Is "Build" supposed to be a folder? Cause for some reason, it isn't there.

It should appear after you've run the build.bat.

> disable the time stop animation

There is no animation, the entities aren't moving. Your lag is partly from 1.15 being 1.15 and mostly from the effect effecting every entity in the world.

**Comment by thedeerirty** [comment]
> > Is that normal, and should I just wait?
> 
> It is, just wait for a while and then check the folder.

Alright cool, I'll let it sit for an hour or so.

> 1.15 and possibly 1.16 this month, 1.12 would be late next month if I started work on it right now. Fabric would be late October or November, really hard to port.

While I am excited for a 1.12 port, maybe a little break or something might do ya' some good, if you need one? Don't need to overwork yourself on this.

**Comment by Novarch129** [comment]
> Is there a Discord

Finally finished it today, link can be found in the [README](https://github.com/Novarch129/JoJo-s-Bizarre-Survival/blob/1.15.x/README.md).

**Comment by Novarch129** [comment]
Closing this in favor of discussion on the Discord.
