### ISSUE TITLE
Instructions not clear. My stands won't upgrade.

### ISSUE THREAD

**Issue by DanDragonWolf** [Novarch129/JoJo-s-Bizarre-Survival#22]
I am not able to upgrade any upgradeable stand. I can't even upgrade Golden Experience to it's Requiem form. I know I need lots of xp for Tusk and Echoes, but I don't know how to use the xp to upgrade them. When I try to get GER, the game sends a message in chat telling me that I already have a stand. To clarify things, I am using commands to give myself xp. If that has anything to do with it, then let me know.

**Comment by Novarch129** [comment]
You need 1000, 3000 and 8000 xp **points** for Echoes and Tusk (in order). Giving yourself too much can prevent you from obtaining them. To get GER you need to get 1 000 000 xp points and use the default Stand arrow. If you're doing it with commands, using `/stand evolve` might be more efficient.

**Comment by DanDragon401** [comment]
I was just trying to test stand upgrades before I decide to use the mod In a survival world. I also want to know how to upgrade Whitesnake. I looked at the code and found out the amount of xp for Killer Queen. Also,

**Comment by DanDragonWolf** [comment]
Oops, wrong button lol.

**Comment by DanDragonWolf** [comment]
I was just wanting to test stand upgrades before I use this in a survival world. I also noticed that you can't remove GER once you have it unless if you use commands. I also want to know how to upgrade Whitesnake.

**Comment by Novarch129** [comment]
Just use more Xp, 8000 points for C-Moon. I'm closing this because it isn't even an issue.
