### ISSUE TITLE
Can I obtain or craft arrows in survival mode?

### ISSUE THREAD

**Issue by YKITV7I7T7T** [Novarch129/JoJo-s-Bizarre-Survival#24]
I have always wanted to survive with this mod, but I don’t know how to get arrows in survival mode or I can’t get arrows in survival yet.
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
If the current version can no longer create or obtain arrows in survival mode, let me give the author some opinions: 1. You can add a meteorite, but you need to use diamonds to remove it, and standing on it will give it a withering effect. 2. Let him in some ruins Box appears (no need to add relics, just let the arrows appear in the box) 3. New NPCs can buy arrows

**Comment by thedeerirty** [comment]
Hiyo, I'm not the developer, but the model maker and the moderator on the discord server.

Currently, stand arrows are found in extremely rare desert structures. The structure is a bit bugged at the moment, but the arrow is still obtainable through it.

**Comment by thedeerirty** [comment]
The stand arrow in the structure can also be crafted to gain specific stands.

**Comment by Novarch129** [comment]
Joe's comment explains it pretty well, closed.
