### ISSUE TITLE
Is it normal for Stands to disappear after my death?

### ISSUE THREAD

**Issue by YKITV7I7T7T** [Novarch129/JoJo-s-Bizarre-Survival#26]
My Stands will disappear every time I die. I’m going crazy lol

**Comment by giothemoonwalker** [comment]
Yeah, it's normal, but you can change it in the mod's config

**Comment by YKITV7I7T7T** [comment]
> 是的，這很正常，但是您可以在mod的配置中進行更改

How to modify the mod

**Comment by Novarch129** [comment]
> How to modify the mod
Use the config file in Appdata/.minecraft/config.
