### ISSUE TITLE
Time stop ability looping / How to activate Bite The Dust

### ISSUE THREAD

**Issue by Euxiohaha** [Novarch129/JoJo-s-Bizarre-Survival#29]
-Star Platinum and The World time-stop ability sometimes loops itself and cause my minecraft to not responding.
-Also how do I activate bite the dust?

**Comment by nanoandy228** [comment]
-There is an Ability Toggle in the keyboard setting
-you can't

**Comment by Novarch129** [comment]
- The ability loops while it is on, use the ability toggle button listed in the controls to turn it off.
- First evolve your Killer Queen by using `/stand evolve @s` and then press Shift+X while Killer Queen is summoned to place a checkpoint, press Shift+X again or wait 1 Minecraft day for it to rewind to that point.
