### ISSUE TITLE
Bugged Golden Experience life form giver

### ISSUE THREAD

**Issue by yeetman255** [Novarch129/JoJo-s-Bizarre-Survival#31]
Hello, i'm here to tell you that the life form giver ability doesn't work well on different blocks that are not dirt or stone. It took me 5 attempts to summon a husk from a sand block and i could summon a spider from a cobweb just 1 time. So that's it, life form giver takes a lot to work on blocks that are not dirt or stone. I hope you fix this, thank you for taking your time reading this if you did.

**Comment by Novarch129** [comment]
Cannot replicate, you're doing something wrong.
