### ISSUE TITLE
How can this mod to stop destroy blocks

### ISSUE THREAD

**Issue by midoriwuri** [Novarch129/JoJo-s-Bizarre-Survival#34]
this is a great mod,but my attack always broken everything,maybe Profile text can change this function,but i'm loser.i won't,i think even this mod can't broke blocks,it's still be a realy good fun mod,is someguys can tell me how to modify this? my realy thanks(:

**Comment by midoriwuri** [comment]
another thing,aerosmith is so hard control,that's...bad feels.

**Comment by Novarch129** [comment]
Config options, if you don't know how to edit configs Google it.
